services:
  postgres:
    image: postgres:15
    container_name: postgres_snowflake_bd
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lab
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./:/opt/project

volumes:
  postgres_data: